name: health_sync_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.65.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flip_card: ^0.7.0
  # home_widget: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/static/Inter-Regular.ttf
